from __future__ import annotations

DEFAULT_REQUEST_TIMEOUT = 20
DEFAULT_FOOD_PER_DAY = 120.0
DEFAULT_HOTEL_PER_NIGHT = 250.0
DEFAULT_TICKET_COST = 200.0
DEFAULT_TRANSPORT_COST = 0.0
DEFAULT_POI_LIMIT = 10
MAX_FORECAST_DAYS = 7
MAX_ATTRACTION_LIMIT = 20
MAX_BUDGET_DAYS = 14

